plugins {
	id 'java'
	id 'com.github.bjornvester.xjc' version '1.9.1' // https://github.com/bjornvester/xjc-gradle-plugin
	id 'idea'
	id 'groovy' // For Spock tests
}

group = 'info.hubbitus'
version = '1.0-SNAPSHOT'

java {
	toolchain { languageVersion = JavaLanguageVersion.of(11) }
}

repositories {
	mavenCentral()
}

ext{
	pluginVersion = '1.1'
}

dependencies {
	xjcPlugins "info.hubbitus:xjc-documentation-annotation-plugin:$pluginVersion"

	// Compile dependency for annotations used
	implementation "info.hubbitus:xjc-documentation-annotation-plugin:$pluginVersion"
	testImplementation "info.hubbitus:xjc-documentation-annotation-plugin:$pluginVersion"

	// Tests
	testImplementation 'org.apache.groovy:groovy:5.1.3'
	testImplementation 'org.spockframework:spock-core:2.4-groovy-5.0'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher' // Required by Gradle 9 (version is managed by Spock BOM)
}

tasks.withType(Test).configureEach {
	useJUnitPlatform() // Spock 2
}

// Results will be in directory `build/generated/sources/xjc/java`
xjc {
	/**
	 * There:
	 * 1. Example.xsd is minimal example of functional.
	 * 2. maven-4.0.0.xsd - example by SOq https://stackoverflow.com/questions/42223784/how-can-i-generate-a-class-from-which-i-can-retrieve-the-xml-of-a-node-as-a-stri
	 */
	xsdDir = layout.projectDirectory.dir('src/main/resources')
	bindingFiles = fileTree('src/main/resources') { include '*.xjb' }
	useJakarta = false // The plugin is built on javax (JAXB 2.x) XJC API
	defaultPackage = 'info.hubbitus.xjc.plugin.example'
	options = [ '-XPluginDescriptionAnnotation' ]
}
